# Generated by Django 6.0.3 on 2026-03-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedDRACode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('preferred_term', models.CharField(db_index=True, max_length=500)),
                ('soc_code', models.CharField(blank=True, help_text='System Organ Class code', max_length=20, null=True)),
                ('soc_name', models.CharField(blank=True, help_text='System Organ Class name', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'MedDRA Code',
                'verbose_name_plural': 'MedDRA Codes',
                'db_table': 'meddra_codes',
            },
        ),
        migrations.CreateModel(
            name='AdverseEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_report_id', models.CharField(db_index=True, help_text='External report ID', max_length=50, unique=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('is_serious', models.BooleanField(default=False)),
                ('seriousness_death', models.BooleanField(default=False)),
                ('seriousness_hospitalization', models.BooleanField(default=False)),
                ('seriousness_disability', models.BooleanField(default=False)),
                ('seriousness_lifethreatening', models.BooleanField(default=False)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, help_text='M=Male, F=Female, U=Unknown', max_length=1, null=True)),
                ('source', models.CharField(choices=[('openfda_events', 'OpenFDA Drug Events'), ('fda_csv', 'FDA Adverse Events CSV'), ('synthetic', 'Synthetic/ADR Data')], max_length=50)),
                ('source_file', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adverse_event_reports',
                'indexes': [models.Index(fields=['report_date'], name='idx_report_date'), models.Index(fields=['is_serious'], name='idx_report_serious'), models.Index(fields=['source'], name='idx_report_source')],
            },
        ),
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_term', models.CharField(db_index=True, help_text='MedDRA Preferred Term or reaction name', max_length=500, unique=True)),
                ('preferred_term_normalized', models.CharField(db_index=True, max_length=500)),
                ('meddra_code', models.CharField(blank=True, db_index=True, help_text='MedDRA code', max_length=20, null=True)),
                ('severity_category', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adverse_reactions',
                'ordering': ['preferred_term'],
                'indexes': [models.Index(fields=['preferred_term_normalized'], name='idx_reaction_normalized'), models.Index(fields=['meddra_code'], name='idx_reaction_meddra')],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, help_text='Normalized lowercase drug name', max_length=500, unique=True)),
                ('rxcui', models.CharField(blank=True, db_index=True, help_text='RxNorm Concept Unique Identifier', max_length=20, null=True)),
                ('pubchem_cid', models.CharField(blank=True, help_text='PubChem Compound ID', max_length=50, null=True)),
                ('is_combination', models.BooleanField(default=False, help_text='True if this is a multi-drug combination product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drugs',
                'ordering': ['canonical_name'],
                'indexes': [models.Index(fields=['canonical_name'], name='idx_drug_canonical'), models.Index(fields=['rxcui'], name='idx_drug_rxcui')],
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, unique=True)),
                ('name_normalized', models.CharField(db_index=True, max_length=500)),
                ('meddra_code', models.CharField(blank=True, db_index=True, help_text='MedDRA code if available', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indications',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name_normalized'], name='idx_indication_normalized')],
            },
        ),
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(help_text='The contraindication condition')),
                ('condition_normalized', models.CharField(db_index=True, help_text='Normalized for matching', max_length=500)),
                ('severity', models.CharField(choices=[('absolute', 'Absolute - Never Use'), ('relative', 'Relative - Use With Extreme Caution')], default='absolute', max_length=20)),
                ('source', models.CharField(choices=[('fda_label', 'FDA Drug Label'), ('sider', 'SIDER Dataset')], max_length=50)),
                ('source_label_id', models.CharField(blank=True, help_text='FDA label ID if from labels', max_length=100, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='data_access.drug')),
            ],
            options={
                'db_table': 'contraindications',
                'indexes': [models.Index(fields=['condition_normalized'], name='idx_contraindication_norm'), models.Index(fields=['drug', 'severity'], name='idx_contraindication_drug')],
            },
        ),
        migrations.CreateModel(
            name='DrugAdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, choices=[('very_common', '>10%'), ('common', '1-10%'), ('uncommon', '0.1-1%'), ('rare', '0.01-0.1%'), ('very_rare', '<0.01%'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('report_count', models.IntegerField(default=0, help_text='Number of reports linking this drug-reaction pair')),
                ('source', models.CharField(choices=[('fda_label', 'FDA Drug Label'), ('sider', 'SIDER Dataset'), ('faers', 'FAERS Database'), ('synthetic', 'Synthetic/ADR Data')], max_length=50)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='data_access.drug')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='data_access.adversereaction')),
            ],
            options={
                'db_table': 'drug_adverse_reactions',
                'indexes': [models.Index(fields=['drug', 'report_count'], name='idx_drug_reaction_count')],
                'unique_together': {('drug', 'reaction', 'source')},
            },
        ),
        migrations.CreateModel(
            name='DrugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='The alias name as-is', max_length=500)),
                ('alias_normalized', models.CharField(db_index=True, help_text='Lowercase normalized for matching', max_length=500)),
                ('alias_type', models.CharField(choices=[('brand', 'Brand Name'), ('generic', 'Generic Name'), ('variant', 'Spelling Variant'), ('substance', 'Active Substance'), ('combination', 'Combination Product')], default='generic', max_length=20)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='data_access.drug')),
            ],
            options={
                'db_table': 'drug_aliases',
                'indexes': [models.Index(fields=['alias_normalized'], name='idx_alias_normalized'), models.Index(fields=['alias_type'], name='idx_alias_type')],
                'unique_together': {('drug', 'alias_normalized')},
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('contraindicated', 'Contraindicated - Do Not Use Together'), ('major', 'Major - Serious Consequences Likely'), ('moderate', 'Moderate - Use With Caution'), ('minor', 'Minor - Minimal Clinical Significance'), ('unknown', 'Unknown Severity')], db_index=True, default='unknown', max_length=20)),
                ('description', models.TextField(help_text='Description of the interaction')),
                ('clinical_effect', models.TextField(blank=True, help_text='What happens clinically', null=True)),
                ('management', models.TextField(blank=True, help_text='How to manage this interaction', null=True)),
                ('evidence_level', models.CharField(blank=True, choices=[('established', 'Established'), ('probable', 'Probable'), ('suspected', 'Suspected'), ('theoretical', 'Theoretical')], max_length=20, null=True)),
                ('source', models.CharField(choices=[('fda_label', 'FDA Drug Label'), ('faers', 'FAERS Database'), ('sider', 'SIDER Dataset'), ('synthetic', 'Synthetic/ADR Data')], max_length=50)),
                ('source_label_id', models.CharField(blank=True, help_text='FDA label ID if from labels', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='data_access.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='data_access.drug')),
            ],
            options={
                'db_table': 'drug_interactions',
                'indexes': [models.Index(fields=['drug_a', 'severity'], name='idx_interaction_a_severity'), models.Index(fields=['drug_b', 'severity'], name='idx_interaction_b_severity'), models.Index(fields=['severity'], name='idx_interaction_severity')],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='EventReportDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterization', models.CharField(choices=[('suspect', 'Primary Suspect'), ('concomitant', 'Concomitant'), ('interacting', 'Interacting')], default='suspect', max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('indication', models.CharField(blank=True, help_text='Why the drug was taken', max_length=500, null=True)),
                ('drug_name_raw', models.CharField(blank=True, help_text='Original drug name from report', max_length=500, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reports', to='data_access.drug')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='data_access.adverseeventreport')),
            ],
            options={
                'db_table': 'event_report_drugs',
                'indexes': [models.Index(fields=['drug', 'characterization'], name='idx_event_drug_char')],
            },
        ),
        migrations.CreateModel(
            name='EventReportReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('recovering', 'Recovering'), ('not_recovered', 'Not Recovered'), ('fatal', 'Fatal'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('reaction_name_raw', models.CharField(blank=True, help_text='Original reaction name from report', max_length=500, null=True)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reports', to='data_access.adversereaction')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='data_access.adverseeventreport')),
            ],
            options={
                'db_table': 'event_report_reactions',
                'indexes': [models.Index(fields=['reaction'], name='idx_event_reaction')],
            },
        ),
        migrations.CreateModel(
            name='DrugIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fda_label', 'FDA Drug Label'), ('sider', 'SIDER Dataset'), ('faers', 'FAERS Database'), ('synthetic', 'Synthetic/ADR Data')], max_length=50)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0.0-1.0')),
                ('source_text', models.TextField(blank=True, help_text='Original text from source', null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='data_access.drug')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='data_access.indication')),
            ],
            options={
                'db_table': 'drug_indications',
                'unique_together': {('drug', 'indication', 'source')},
            },
        ),
    ]
