# Generated by Django 6.0.3 on 2026-03-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('same_class', 'Same Therapeutic Class'), ('similar_mechanism', 'Similar Mechanism of Action'), ('fewer_side_effects', 'Fewer Side Effects'), ('fewer_interactions', 'Fewer Drug Interactions'), ('safer_profile', 'Safer Overall Profile'), ('otc_alternative', 'OTC Alternative'), ('prescription_alternative', 'Prescription Alternative')], default='same_class', max_length=50)),
                ('advantages', models.TextField(blank=True, help_text='Benefits of this alternative (JSON list or comma-separated)', null=True)),
                ('considerations', models.TextField(blank=True, help_text='Things to consider with this alternative (JSON list or comma-separated)', null=True)),
                ('similarity_score', models.FloatField(default=0.8, help_text='How similar the therapeutic effect is (0.0-1.0)')),
                ('is_otc', models.BooleanField(default=True, help_text='Is the alternative available over-the-counter?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_drug', models.ForeignKey(help_text='The suggested alternative drug', on_delete=django.db.models.deletion.CASCADE, related_name='alternatives_to', to='data_access.drug')),
                ('original_drug', models.ForeignKey(help_text='The drug being replaced', on_delete=django.db.models.deletion.CASCADE, related_name='alternatives_from', to='data_access.drug')),
            ],
            options={
                'db_table': 'drug_alternatives',
                'indexes': [models.Index(fields=['original_drug'], name='idx_alt_original'), models.Index(fields=['alternative_drug'], name='idx_alt_alternative'), models.Index(fields=['reason'], name='idx_alt_reason')],
                'unique_together': {('original_drug', 'alternative_drug')},
            },
        ),
    ]
