"""
Django settings for medguard project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env(key: str, default: str = "") -> str:
    """Get environment variable with optional default."""
    return os.environ.get(key, default)


def get_env_bool(key: str, default: bool = False) -> bool:
    """Get boolean environment variable."""
    return get_env(key, str(default)).lower() in ("true", "1", "yes")


def get_env_list(key: str, default: str = "") -> list[str]:
    """Get comma-separated environment variable as list."""
    value = get_env(key, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Load .env file if it exists (for local development)
env_path = BASE_DIR / ".env"
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key.strip(), value.strip())


# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env(
    "DJANGO_SECRET_KEY",
    "django-insecure-o_a##_)6nf72lr(&&+2nm^1y+p41bro^ctepnl7)y92t(myu4(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # MedGuard apps
    "apps.data_access",
    "apps.pipeline",
    "apps.frontend",
    "medguard_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "medguard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "medguard.wsgi.application"


# =============================================================================
# DATABASE
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# =============================================================================

db_engine = get_env("DB_ENGINE", "django.db.backends.sqlite3")

if db_engine == "django.db.backends.mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": get_env("DB_NAME", "medguard"),
            "USER": get_env("DB_USER", "root"),
            "PASSWORD": get_env("DB_PASSWORD", ""),
            "HOST": get_env("DB_HOST", "localhost"),
            "PORT": get_env("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    # Default to SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# =============================================================================
# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =============================================================================
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# =============================================================================

STATIC_URL = "static/"


# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# MEDGUARD CUSTOM SETTINGS
# =============================================================================

# Data paths
DATA_RAW_PATH = Path(get_env("DATA_RAW_PATH", str(BASE_DIR / "data" / "raw")))
DATA_PROCESSED_PATH = Path(
    get_env("DATA_PROCESSED_PATH", str(BASE_DIR / "data" / "processed"))
)
DATA_LOGS_PATH = Path(
    get_env("DATA_LOGS_PATH", str(BASE_DIR / "data" / "processed" / "processing_logs"))
)

# ChromaDB settings
CHROMADB_PATH = get_env("CHROMADB_PATH", str(BASE_DIR / "data" / "chromadb"))
CHROMADB_COLLECTION_PREFIX = get_env("CHROMADB_COLLECTION_PREFIX", "medguard_")

# Embedding model settings
EMBEDDING_MODEL = get_env("EMBEDDING_MODEL", "BAAI/bge-base-en-v1.5")
EMBEDDING_DEVICE = get_env("EMBEDDING_DEVICE", "cpu")
EMBEDDING_BATCH_SIZE = int(get_env("EMBEDDING_BATCH_SIZE", "32"))

# HuggingFace settings (for faster model downloads)
HUGGINGFACE_TOKEN = get_env("HF_TOKEN", "")

# DeepSeek API settings
DEEPSEEK_API_KEY = get_env("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = get_env("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = get_env("DEEPSEEK_MODEL", "deepseek-chat")

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": get_env("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "medguard": {
            "handlers": ["console"],
            "level": get_env("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
